spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 1234

    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 60000
      connection-init-sql: SELECT 1