spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music
    username: root
    password: 1234

    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 60000
      connection-init-sql: SELECT 1

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1005699460275-5lj3s3e6bemht5tks42l96qiv7stts51.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile

jwt:
  issuer: dydrnxke@gmail.com
  secret_ket: jwt-study