spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music
    username: root
    password: 1234

    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 60000
      connection-init-sql: SELECT 1

oauth2:
  user:
      client-id: 1005699460275-5lj3s3e6bemht5tks42l96qiv7stts51.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: http://localhost:6080/login/oauth2/code/google

  provider:
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

jwt:
  token:
    secret-key: secret_key